# Generated by Django 5.2.4 on 2026-04-22 22:23

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('consultation_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_consultation', models.DateTimeField()),
                ('motif', models.CharField(max_length=255)),
                ('diagnostic_principal', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'db_table': 'consultation',
                'ordering': ['-date_consultation'],
            },
        ),
        migrations.CreateModel(
            name='ExamenMedical',
            fields=[
                ('examen_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_examen', models.CharField(max_length=255)),
                ('type_examen', models.CharField(choices=[('biologie', 'Biologie'), ('imagerie', 'Imagerie'), ('ecg', 'Électrocardiogramme'), ('radiologie', 'Radiologie'), ('scanner', 'Scanner'), ('irm', 'IRM'), ('echographie', 'Échographie'), ('endoscopie', 'Endoscopie'), ('autre', 'Autre')], default='biologie', max_length=50)),
                ('resultat', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('fichier_resultat', models.FileField(blank=True, max_length=255, null=True, upload_to='examens/')),
                ('date_examen', models.DateTimeField()),
                ('date_resultat', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Examen Médical',
                'verbose_name_plural': 'Examens Médicaux',
                'db_table': 'examen_medical',
                'ordering': ['-date_examen'],
            },
        ),
        migrations.CreateModel(
            name='GroupeSanguin',
            fields=[
                ('groupe_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Groupe Sanguin',
                'verbose_name_plural': 'Groupes Sanguins',
                'db_table': 'groupe_sanguin',
            },
        ),
        migrations.CreateModel(
            name='LignePrescription',
            fields=[
                ('ligne_id', models.AutoField(primary_key=True, serialize=False)),
                ('medicament_nom', models.CharField(max_length=150)),
                ('forme_pharmaceutique', models.CharField(max_length=100)),
                ('posologie', models.CharField(max_length=255)),
                ('duree_traitement', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Ligne de Prescription',
                'verbose_name_plural': 'Lignes de Prescription',
                'db_table': 'ligne_prescription',
            },
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('medecin_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin'), ('Autre', 'Autre')], max_length=10, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('email_professionnel', models.EmailField(blank=True, max_length=100, null=True, validators=[django.core.validators.EmailValidator()])),
                ('numero_identification', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_matricule_professionnel', models.CharField(blank=True, max_length=50, null=True)),
                ('cree_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Médecin',
                'verbose_name_plural': 'Médecins',
                'db_table': 'medecin',
            },
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('ordonnance_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_ordonnance', models.DateTimeField()),
                ('recommandations', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ordonnance',
                'verbose_name_plural': 'Ordonnances',
                'db_table': 'ordonnance',
                'ordering': ['-date_ordonnance'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('dosage', models.CharField(max_length=100)),
                ('frequence', models.CharField(max_length=100)),
                ('duree', models.CharField(max_length=100)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'db_table': 'prescription',
            },
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('specialite_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_specialite', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Spécialité',
                'verbose_name_plural': 'Spécialités',
                'db_table': 'specialite',
                'ordering': ['nom_specialite'],
            },
        ),
    ]
