# Generated by Django 5.2.4 on 2026-04-22 20:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_tenants', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_tenants.tenant')),
            ],
            options={
                'db_table': 'equipement',
            },
        ),
        migrations.CreateModel(
            name='SalleMedicale',
            fields=[
                ('salle_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('capacite', models.IntegerField(default=1)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('occupee', 'Occupée'), ('maintenance', 'En maintenance')], default='disponible', max_length=20)),
                ('duree_consultation_defaut', models.IntegerField(default=30)),
                ('prix_par_seance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('est_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_tenants.tenant')),
            ],
            options={
                'db_table': 'salle_medicale',
            },
        ),
        migrations.CreateModel(
            name='AffectationSalle',
            fields=[
                ('affectation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(blank=True, max_length=100)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('medecin', models.ForeignKey(blank=True, limit_choices_to={'role': 'medecin'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salles.sallemedicale')),
            ],
            options={
                'db_table': 'affectation_salle',
            },
        ),
        migrations.CreateModel(
            name='TypeSalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_tenants.tenant')),
            ],
            options={
                'db_table': 'type_salle',
            },
        ),
        migrations.AddField(
            model_name='sallemedicale',
            name='type_salle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salles.typesalle'),
        ),
        migrations.CreateModel(
            name='SalleEquipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salles.equipement')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salles.sallemedicale')),
            ],
            options={
                'db_table': 'salle_equipement',
                'unique_together': {('salle', 'equipement')},
            },
        ),
        migrations.CreateModel(
            name='PlanningSalle',
            fields=[
                ('planning_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('motif', models.CharField(blank=True, max_length=255)),
                ('statut', models.CharField(choices=[('reservee', 'Réservée'), ('confirmee', 'Confirmée'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='reservee', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('medecin', models.ForeignKey(limit_choices_to={'role': 'medecin'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salles.sallemedicale')),
            ],
            options={
                'db_table': 'planning_salle',
                'unique_together': {('salle', 'date', 'heure_debut')},
            },
        ),
    ]
