# Generated by Django 5.2.4 on 2026-04-22 22:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lit',
            fields=[
                ('lit_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_lit', models.CharField(max_length=20)),
                ('statut', models.CharField(choices=[('libre', 'Libre'), ('occupe', 'Occupé'), ('nettoyage', 'Nettoyage')], default='libre', max_length=20)),
            ],
            options={
                'db_table': 'lit',
            },
        ),
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('chambre_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_chambre', models.CharField(max_length=20)),
                ('etage', models.IntegerField()),
                ('capacite', models.IntegerField()),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('occupe', 'Occupée'), ('maintenance', 'Maintenance')], default='disponible', max_length=20)),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_tenants.tenant')),
            ],
            options={
                'db_table': 'chambre',
            },
        ),
        migrations.CreateModel(
            name='Hospitalisation',
            fields=[
                ('hospitalisation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_entree', models.DateTimeField(auto_now_add=True)),
                ('date_sortie', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='en_cours', max_length=20)),
                ('motif', models.TextField(blank=True)),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_tenants.tenant')),
            ],
            options={
                'db_table': 'hospitalisation',
            },
        ),
    ]
