# Generated by Django 5.2.4 on 2026-04-22 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitalisation', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalisation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitalisations', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='lit',
            name='chambre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lits', to='hospitalisation.chambre'),
        ),
        migrations.AddField(
            model_name='hospitalisation',
            name='lit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospitalisation.lit'),
        ),
        migrations.AlterUniqueTogether(
            name='chambre',
            unique_together={('hopital', 'numero_chambre')},
        ),
    ]
