# Generated by Django 5.2.4 on 2026-04-22 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('comptes', '0001_initial'),
        ('gestion_tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='hopital',
            field=models.ForeignKey(blank=True, db_column='hopital_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='gestion_tenants.tenant'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='modifie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs_modifies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='utilisateur',
            index=models.Index(fields=['email'], name='utilisateur_email_5ac882_idx'),
        ),
        migrations.AddIndex(
            model_name='utilisateur',
            index=models.Index(fields=['role'], name='utilisateur_role_8f1c1b_idx'),
        ),
        migrations.AddIndex(
            model_name='utilisateur',
            index=models.Index(fields=['hopital'], name='utilisateur_hopital_b6f282_idx'),
        ),
    ]
