# Generated by Django 5.2.4 on 2026-04-18 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('comptes', '0001_initial'),
        ('gestion_tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='hopital',
            field=models.ForeignKey(blank=True, db_column='hopital_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='gestion_tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='utilisateur',
            index=models.Index(fields=['hopital'], name='utilisateur_hopital_b6f282_idx'),
        ),
    ]
