# Generated by Django 5.2.4 on 2026-04-22 22:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('tenant_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('email_professionnel', models.EmailField(blank=True, max_length=100, null=True)),
                ('directeur', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_de_lits', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('numero_enregistrement', models.CharField(blank=True, max_length=100, null=True)),
                ('documents_justificatifs', models.TextField(blank=True, null=True)),
                ('statut_verification_document', models.CharField(choices=[('en_attente', 'En attente'), ('verifie', 'Vérifié'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('suspendu', 'Suspendu')], default='actif', max_length=20)),
                ('type_abonnement', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], default='basic', max_length=20)),
                ('date_verification', models.DateTimeField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('nom_schema_base_de_donnees', models.CharField(blank=True, max_length=255, null=True)),
                ('cree_par_utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants_crees', to=settings.AUTH_USER_MODEL)),
                ('proprietaire_utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants_proprietaires', to=settings.AUTH_USER_MODEL)),
                ('verifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants_verifies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'db_table': 'tenant',
            },
        ),
        migrations.CreateModel(
            name='ParametreHopital',
            fields=[
                ('parametre_id', models.AutoField(primary_key=True, serialize=False)),
                ('fuseau_horaire', models.CharField(default='Europe/Paris', max_length=50)),
                ('langue', models.CharField(default='fr', max_length=10)),
                ('devise', models.CharField(default='EUR', max_length=10)),
                ('duree_consultation_defaut', models.IntegerField(default=30)),
                ('notify_rdv_avance', models.BooleanField(default=True)),
                ('notify_rdv_jour', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('tva_taux', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='gestion_tenants.tenant')),
            ],
            options={
                'verbose_name': 'Paramètre Hôpital',
                'verbose_name_plural': 'Paramètres Hôpitaux',
                'db_table': 'parametre_hopital',
            },
        ),
    ]
