# Generated by Django 5.2.4 on 2026-04-22 22:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonnementStatut',
            fields=[
                ('statut_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "Statut d'abonnement",
                'verbose_name_plural': "Statuts d'abonnement",
                'db_table': 'abonnement_statut',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('coupon_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('type_reduction', models.CharField(choices=[('pourcentage', 'Pourcentage'), ('fixe', 'Fixe')], max_length=20)),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('utilisation_max', models.IntegerField(blank=True, null=True)),
                ('utilisations_actuelles', models.IntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'db_table': 'coupon',
            },
        ),
        migrations.CreateModel(
            name='InvoiceStatut',
            fields=[
                ('statut_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Statut de facture',
                'verbose_name_plural': 'Statuts de facture',
                'db_table': 'invoice_statut',
            },
        ),
        migrations.CreateModel(
            name='PaiementMethode',
            fields=[
                ('methode_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Méthode de paiement',
                'verbose_name_plural': 'Méthodes de paiement',
                'db_table': 'paiement_methode',
            },
        ),
        migrations.CreateModel(
            name='PaiementStatut',
            fields=[
                ('statut_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Statut de paiement',
                'verbose_name_plural': 'Statuts de paiement',
                'db_table': 'paiement_statut',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('prix_mensuel', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('prix_annuel', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_utilisateurs', models.IntegerField(default=5)),
                ('max_patients', models.IntegerField(default=100)),
                ('max_stockage', models.IntegerField(default=1024)),
                ('support_telephone', models.BooleanField(default=False)),
                ('formation', models.BooleanField(default=False)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'db_table': 'plan',
            },
        ),
        migrations.CreateModel(
            name='TarifConsultation',
            fields=[
                ('tarif_id', models.AutoField(primary_key=True, serialize=False)),
                ('tarif_normal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('tarif_urgence', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('tarif_nuit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('tarif_weekend', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('duree_consultation', models.IntegerField(default=30)),
                ('actif', models.BooleanField(default=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tarif Consultation',
                'verbose_name_plural': 'Tarifs Consultation',
                'db_table': 'tarif_consultation',
            },
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('abonnement_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='gestion_tenants.tenant')),
                ('statut', models.ForeignKey(db_column='statut_id', on_delete=django.db.models.deletion.CASCADE, to='facturation.abonnementstatut')),
                ('plan', models.ForeignKey(db_column='plan_id', on_delete=django.db.models.deletion.CASCADE, to='facturation.plan')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'db_table': 'abonnement',
            },
        ),
        migrations.CreateModel(
            name='CouponTenant',
            fields=[
                ('coupon_tenant_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_utilisation', models.DateTimeField()),
                ('montant_avant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('montant_apres', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('coupon', models.ForeignKey(db_column='coupon_id', on_delete=django.db.models.deletion.CASCADE, to='facturation.coupon')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='gestion_tenants.tenant')),
            ],
            options={
                'verbose_name': 'Coupon utilisé par tenant',
                'verbose_name_plural': 'Coupons utilisés par tenants',
                'db_table': 'coupon_tenant',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('paiement_id', models.AutoField(primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_paiement', models.DateTimeField()),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('abonnement', models.ForeignKey(db_column='abonnement_id', on_delete=django.db.models.deletion.CASCADE, to='facturation.abonnement')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='gestion_tenants.tenant')),
                ('methode', models.ForeignKey(db_column='methode_id', on_delete=django.db.models.deletion.CASCADE, to='facturation.paiementmethode')),
                ('statut', models.ForeignKey(db_column='statut_id', on_delete=django.db.models.deletion.CASCADE, to='facturation.paiementstatut')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'db_table': 'paiement',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_facture', models.CharField(max_length=50, unique=True)),
                ('date_emission', models.DateTimeField()),
                ('date_echeance', models.DateTimeField(blank=True, null=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('tva', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('url_pdf', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='gestion_tenants.tenant')),
                ('statut', models.ForeignKey(db_column='statut_id', on_delete=django.db.models.deletion.CASCADE, to='facturation.invoicestatut')),
                ('paiement', models.OneToOneField(db_column='paiement_id', on_delete=django.db.models.deletion.CASCADE, to='facturation.paiement')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'db_table': 'invoice',
            },
        ),
        migrations.CreateModel(
            name='AbonnementRenouvellement',
            fields=[
                ('renouvellement_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_renouvellement', models.DateTimeField()),
                ('periode_mois', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('abonnement', models.ForeignKey(db_column='abonnement_id', on_delete=django.db.models.deletion.CASCADE, to='facturation.abonnement')),
                ('paiement', models.ForeignKey(db_column='paiement_id', on_delete=django.db.models.deletion.CASCADE, to='facturation.paiement')),
            ],
            options={
                'verbose_name': "Renouvellement d'abonnement",
                'verbose_name_plural': "Renouvellements d'abonnement",
                'db_table': 'abonnement_renouvellement',
            },
        ),
        migrations.CreateModel(
            name='EssaiGratuit',
            fields=[
                ('essai_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='gestion_tenants.tenant')),
                ('plan', models.ForeignKey(db_column='plan_id', on_delete=django.db.models.deletion.CASCADE, to='facturation.plan')),
            ],
            options={
                'verbose_name': 'Essai gratuit',
                'verbose_name_plural': 'Essais gratuits',
                'db_table': 'essai_gratuit',
            },
        ),
        migrations.AddField(
            model_name='coupon',
            name='plans_valides',
            field=models.ManyToManyField(blank=True, to='facturation.plan'),
        ),
    ]
