# Generated by Django 5.2.4 on 2026-04-22 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturation', '0001_initial'),
        ('gestion_tenants', '0001_initial'),
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifconsultation',
            name='specialite',
            field=models.ForeignKey(db_column='specialite_id', on_delete=django.db.models.deletion.CASCADE, to='medical.specialite'),
        ),
        migrations.AddField(
            model_name='tarifconsultation',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='gestion_tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='coupontenant',
            unique_together={('coupon', 'tenant')},
        ),
        migrations.AlterUniqueTogether(
            name='tarifconsultation',
            unique_together={('tenant', 'specialite', 'date_debut')},
        ),
    ]
