# Generated by Django 5.2.4 on 2026-04-22 20:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_tenants', '0001_initial'),
        ('medical', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin'), ('Autre', 'Autre')], max_length=10, null=True)),
                ('numero_dossier_medical', models.CharField(max_length=50, unique=True)),
                ('numero_identification_nationale', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, validators=[django.core.validators.EmailValidator()])),
                ('cree_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('hopital', models.ForeignKey(blank=True, db_column='hopital_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_tenants.tenant')),
                ('utilisateur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_lie', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'db_table': 'patient',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='AssurancePatient',
            fields=[
                ('assurance_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_assurance', models.CharField(max_length=255)),
                ('numero_police', models.CharField(max_length=50)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
            options={
                'verbose_name': 'Assurance Patient',
                'verbose_name_plural': 'Assurances Patients',
                'db_table': 'assurance_patient',
            },
        ),
        migrations.CreateModel(
            name='AntecedentMedical',
            fields=[
                ('antecedent_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_antecedent', models.CharField(choices=[('maladie_chronique', 'Maladie chronique'), ('chirurgie', 'Chirurgie'), ('traumatisme', 'Traumatisme'), ('allergie', 'Allergie'), ('autre', 'Autre')], default='autre', max_length=50)),
                ('description', models.TextField()),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('en_cours', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
            options={
                'verbose_name': 'Antécédent Médical',
                'verbose_name_plural': 'Antécédents Médicaux',
                'db_table': 'antecedent_medical',
            },
        ),
        migrations.CreateModel(
            name='AllergiePatient',
            fields=[
                ('allergie_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_allergie', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('gravite', models.CharField(choices=[('legere', 'Légère'), ('moderee', 'Modérée'), ('severe', 'Sévère'), ('critique', 'Critique')], default='moderee', max_length=20)),
                ('cree_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
            options={
                'verbose_name': 'Allergie Patient',
                'verbose_name_plural': 'Allergies Patients',
                'db_table': 'allergie_patient',
            },
        ),
        migrations.CreateModel(
            name='AdressePatient',
            fields=[
                ('adresse_id', models.AutoField(primary_key=True, serialize=False)),
                ('pays', models.CharField(default='France', max_length=100)),
                ('departement', models.CharField(blank=True, max_length=100, null=True)),
                ('ville', models.CharField(max_length=100)),
                ('adresse_ligne1', models.CharField(max_length=255)),
                ('adresse_ligne2', models.CharField(blank=True, max_length=255, null=True)),
                ('code_postal', models.CharField(max_length=20)),
                ('cree_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
            options={
                'verbose_name': 'Adresse Patient',
                'verbose_name_plural': 'Adresses Patients',
                'db_table': 'adresse_patient',
            },
        ),
        migrations.CreateModel(
            name='PersonneAContacter',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=50)),
                ('relation', models.CharField(blank=True, max_length=100, null=True)),
                ('cree_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
            options={
                'verbose_name': 'Personne à contacter',
                'verbose_name_plural': 'Personnes à contacter',
                'db_table': 'personne_a_contacter',
            },
        ),
        migrations.CreateModel(
            name='SuiviPatient',
            fields=[
                ('suivi_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_suivi', models.DateField()),
                ('poids', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('taille', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('tension_arterielle_systolique', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(250)])),
                ('tension_arterielle_diastolique', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(150)])),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(45)])),
                ('pouls', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(200)])),
                ('frequence_respiratoire', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(60)])),
                ('glycemie', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('observations', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medecin', models.ForeignKey(blank=True, db_column='medecin_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical.medecin')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
            options={
                'verbose_name': 'Suivi Patient',
                'verbose_name_plural': 'Suivis Patients',
                'db_table': 'suivi_patient',
                'ordering': ['-date_suivi'],
            },
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['numero_dossier_medical'], name='patient_numero__29e72f_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['hopital', 'nom'], name='patient_hopital_d117e1_idx'),
        ),
    ]
