# Generated by Django 5.2.4 on 2026-04-22 20:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('template', models.TextField()),
                ('canal', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('application', 'Application'), ('tous', 'Tous')], default='application', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='gestion_tenants.tenant')),
            ],
            options={
                'verbose_name': 'Type de notification',
                'verbose_name_plural': 'Types de notifications',
                'db_table': 'notification_type',
                'unique_together': {('tenant', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='PreferenceNotification',
            fields=[
                ('preference_id', models.AutoField(primary_key=True, serialize=False)),
                ('notifications_email', models.BooleanField(default=True)),
                ('notifications_sms', models.BooleanField(default=False)),
                ('notifications_application', models.BooleanField(default=True)),
                ('notify_rdv_rappel', models.BooleanField(default=True)),
                ('notify_rdv_annulation', models.BooleanField(default=True)),
                ('notify_rdv_confirmation', models.BooleanField(default=True)),
                ('notify_consultation_ajout', models.BooleanField(default=True)),
                ('notify_examen_resultat', models.BooleanField(default=True)),
                ('notify_paiement_success', models.BooleanField(default=True)),
                ('notify_paiement_echec', models.BooleanField(default=True)),
                ('notify_abonnement_expiration', models.BooleanField(default=True)),
                ('notify_securite_connexion', models.BooleanField(default=True)),
                ('notify_security_changement_mdp', models.BooleanField(default=True)),
                ('rappel_rdv_heures', models.IntegerField(default=24)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(db_column='utilisateur_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préférence de notification',
                'verbose_name_plural': 'Préférences de notifications',
                'db_table': 'preference_notification',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('priorite', models.CharField(choices=[('faible', 'Faible'), ('moyenne', 'Moyenne'), ('elevee', 'Élevée'), ('urgent', 'Urgent')], default='moyenne', max_length=20)),
                ('donnees', models.JSONField(blank=True, null=True)),
                ('cible_type', models.CharField(blank=True, max_length=100, null=True)),
                ('cible_id', models.IntegerField(blank=True, null=True)),
                ('est_lu', models.BooleanField(default=False)),
                ('est_envoyee', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_lu', models.DateTimeField(blank=True, null=True)),
                ('date_envoyee', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='gestion_tenants.tenant')),
                ('utilisateur', models.ForeignKey(db_column='utilisateur_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(db_column='type_id', on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationtype')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'utilisateur', 'est_lu'], name='notificatio_tenant__230512_idx'), models.Index(fields=['created_at'], name='notificatio_created_db7ad3_idx')],
            },
        ),
    ]
